<template>
<div class="page-loading">
  <div class="loadingio-spinner-ripple-y40v4tk3f1j">
    <div class="ldio-njz3fo1h3zk">
      <div></div>
      <div></div>
    </div>
  </div>
</div>
</template>
<script>
export default {};
</script>
<style>
@keyframes ldio-njz3fo1h3zk {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 18px;
    left: 18px;
    width: 156px;
    height: 156px;
    opacity: 0;
  }
}
.page-loading {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(255, 255, 255, 0.8);
  z-index: 1;
}
.ldio-njz3fo1h3zk div {
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-njz3fo1h3zk 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.ldio-njz3fo1h3zk div:nth-child(1) {
  border-color: #7508e7;
  animation-delay: 0s;
}
.ldio-njz3fo1h3zk div:nth-child(2) {
  border-color: #46dff0;
  animation-delay: -0.5s;
}
.loadingio-spinner-ripple-y40v4tk3f1j {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%,-50%);

}
.ldio-njz3fo1h3zk {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-njz3fo1h3zk div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
